### ISSUE TITLE
Auth error

### ISSUE THREAD

**Issue by AlexQuidditch** [tchak/todomvc-logux#1]
process.env.NODE_ENV is undefined here

https://github.com/tchak/todomvc-logux/blob/0858fc1de716fe0a7e8ff71bf4c4eace8dd1d9e2/server/index.js#L27

What about it?
```
server.auth(( userId, token ) => {
  // Allow only local users until we will have a proper authentication
  return true;
});
```

**Comment by nevf** [comment]
```The process.env property returns an object containing the user environment.```

So just add ```NODE_ENV=...``` to you PCs environment variables.

**Comment by AlexQuidditch** [comment]
I didn't think about it, thanks!
